/**
 * Created by trainee on 3/2/16.
 */
define(
    [
        './controller/masterController',
        './controller/fileUploadingController',
        './controller/renderListController',
        './controller/uploadContactsController',
        './service/securityContext',
        './service/statePreference',
        './service/schedulingUtil',
        './service/validationMessageBuilder',
        './service/permissionsService',
        './service/recorderService',
        './service/timerService',
        './service/fileUploadingService',
        './service/uploadContactsService',
        './service/model/eventService',
        './service/model/lessonService',
        './service/model/roleService',
        './service/model/stageService',
        './service/model/subjectService',
        './service/model/teacherService',
        './service/model/userService',
        './directive/uploadFile',
        './directive/datetimepicker',
        './directive/setImage',
        './directive/loadingIndicator',
        './directive/httpLoadingIndicator',
        './directive/checkPermissions',
        './directive/dictaphone',
        './directive/renderList',
        './filters/deepFilter',
        './endpoint'
    ],
    function () {
        'use strict';
    }
);